<Project>
  <PropertyGroup Label="Settings">
    <Deterministic>true</Deterministic>
    <LangVersion>14</LangVersion>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <MinVerSkip Condition="'$(Configuration)' == 'Debug'">true</MinVerSkip>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SA1633</NoWarn>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <!-- Disable nullability for netstandard2.0 since polyfills are not -->
  <!-- working correctly with nullability analysis. -->
  <!-- This is no big deal since nullability is checked for other TFMs. -->
  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup Condition="$(IsPackable)">
    <None Include="$(MSBuildThisFileDirectory)../resources/nuget/logo.png">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
      <Link>Properties/Package/Logo.png</Link>
    </None>
    <None Include="$(MSBuildThisFileDirectory)../resources/nuget/$(AssemblyName).md">
      <Pack>true</Pack>
      <PackagePath>\README.md</PackagePath>
      <Link>Properties/Package/README.md</Link>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <Description>A library that makes it easier to create beautiful console applications.</Description>
    <Copyright>Patrik Svensson, Phil Scott, Nils Andresen, Cédric Luthi, Frank Ray</Copyright>
    <Authors>Patrik Svensson, Phil Scott, Nils Andresen, Cédric Luthi, Frank Ray</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/spectreconsole/spectre.console</RepositoryUrl>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/spectreconsole/spectre.console</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>https://github.com/spectreconsole/spectre.console/releases</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseBuildTimeTools)' != 'false'">
    <PackageReference Include="MinVer" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Roslynator.Analyzers">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>